// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddServer'](arg1, arg2, arg3);
}

export function AddServers(arg1) {
  return window['go']['main']['App']['AddServers'](arg1);
}

export function CheckUpdate(arg1) {
  return window['go']['main']['App']['CheckUpdate'](arg1);
}

export function CreateDatabase(arg1, arg2) {
  return window['go']['main']['App']['CreateDatabase'](arg1, arg2);
}

export function CreateDatabaseFromLegacy(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateDatabaseFromLegacy'](arg1, arg2, arg3, arg4);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function Load(arg1, arg2) {
  return window['go']['main']['App']['Load'](arg1, arg2);
}

export function LoadUserConfig() {
  return window['go']['main']['App']['LoadUserConfig']();
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function SaveUserConfig(arg1) {
  return window['go']['main']['App']['SaveUserConfig'](arg1);
}

export function SelectDashboardFile() {
  return window['go']['main']['App']['SelectDashboardFile']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectLegacyDashboardFile() {
  return window['go']['main']['App']['SelectLegacyDashboardFile']();
}

export function TestConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2, arg3);
}

export function Unload() {
  return window['go']['main']['App']['Unload']();
}

export function Update() {
  return window['go']['main']['App']['Update']();
}

export function VerifyLegacy(arg1, arg2) {
  return window['go']['main']['App']['VerifyLegacy'](arg1, arg2);
}
