// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddServer'](arg1, arg2, arg3);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function CreateDatabase(arg1, arg2) {
  return window['go']['main']['App']['CreateDatabase'](arg1, arg2);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Load(arg1, arg2) {
  return window['go']['main']['App']['Load'](arg1, arg2);
}

export function LoadUserConfig() {
  return window['go']['main']['App']['LoadUserConfig']();
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function SaveUserConfig(arg1) {
  return window['go']['main']['App']['SaveUserConfig'](arg1);
}

export function SelectDashboardFile() {
  return window['go']['main']['App']['SelectDashboardFile']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function TestConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2, arg3);
}

export function Unload() {
  return window['go']['main']['App']['Unload']();
}

export function Update() {
  return window['go']['main']['App']['Update']();
}
