// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDatabase(arg1:string,arg2:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function Load(arg1:string,arg2:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function Unload():Promise<void>;
